changelog:
  categories:
    - title: This is the tile for new features
      labels:
        - 'Feature'
    - title: Fixing patches in codebase
      labels:
        - 'Fix'
    - title: Enhancement
      labels:
        - 'Enhancement'
  exclude:
    labels:
      - ignore-for-release
    - title: Build
      labels:
        - 'Build'
    - title: Documentation
      labels:
        - 'Documentation'
    - title: Internal
      labels:
        - 'Internal'
    - title: Refactor
      lables:
        - 'Refactor'
    - title: Test Cases
      labels:
        - '*'
