name: Release Notes Builder

on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Call GitHub Release API
        id: releases
        run: |
          RESPONSE=$(gh api --method POST -H "Accept: application/vnd.github+json" -f tag_name="0.1.10" -f previous_tag_name="0.1.2" -f commitish="Internal" -f configuration_file_path=".github/release.yml" /repos/cortiqa-playground/Release-notes/releases/generate-notes | jq -r .body );
          
          echo "${RESPONSE}" > release_notes.md ;
          ls -l release_notes.md;
          
      - name: Pre-process Release Notes
        run: |
          sed 's/\([.]*\)by @.*/\1/g' release_notes.md > release_notes_processed.md;
          
      - name: Process Release Notes
        run: |
          cat release_notes_processed.md;
