name: Release Notes Builder

on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
###"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"
  
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Call GitHub Release API
        id: releases
        run: |
          RESPONSE=$(gh api --method POST -H 'Accept: application/vnd.github+json' -f tag_name='v0.1.10' /repos/cortiqa-playground/Release-notes/releases/generate-notes);
          echo "Logging ******* ${RESPONSE}";
          echo "${RESPONSE}" > release_notes.json ;
          ls -l release_notes.json;
          
        
      - name: Install jq processor
        uses: sergeysova/jq-action@v2
        id: release_list
        with:
          cmd: "jq .body[] release_notes.json -r"
          multiline: true
      
      - name: Print the value
        run: echo ${{steps.release_list.outputs.value}}
               
      - name: Process Release Notes
        run: |
          for keyword in ${{ steps.release_list.outputs.value }}; do
            echo "$keyword"
          done
