name: Release Notes Builder

on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
###"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"
  
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Call GitHub Release API
        id: release_notes
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/cortiqa-playground/Release-notes/releases
        
      - name: Install jq processor
        uses: sergeysova/jq-action@v2
        id: release_list
        with:
          cmd: "echo {{ steps.release_notes.output.value }} | jq .tag_name[] "
          multiline: true
