name: Test Run

on:
  push:
    branches: [ "main" ]
 
  workflow_dispatch:

env:
  RELEASE_TAG_VERSION: 0.2.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  generate-release-notes:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Generate Release notes 
        run: | 
          RESPONSE=$(gh api --method POST -H "Accept: application/vnd.github+json" -f tag_name=${{env.RELEASE_TAG_VERSION}} -f previous_tag_name="0.1.9" -f commitish="Internal" -f configuration_file_path=".github/release.yml" /repos/cortiqa-playground/Release-notes/releases/generate-notes | jq -r .body );
          <<release_notes_processed.md>>

      - name: Check release file successfully created
        run: |
          cat release_notes.md
          
      - name: Pre-process Release Notes
        run: |
          sed 's/\([.]*\)by @.*/\1/g' release_notes.md > release_notes_processed.md;
          cat release_notes_processed.md

      - name: Create a tag
        run: | 
          echo "Change this text later to run gh api for release"

  deploy:
    needs: generate-release-notes
    runs-on: ubuntu-latest
    steps:
      - name: Check if release notes is attached to the release
        run : |
          cat release_notes_processed.md