name: Test Run

on:
  push:
    branches: [ "main" ]
 
  workflow_dispatch:

env:
  RELEASE_TAG_VERSION: "0.3.4"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RELEASE_NOTES: release_notes.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  generate-release-notes:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Generate Release notes 
        run: | 
          RESPONSE=$(gh api --method POST -H "Accept: application/vnd.github+json" -f tag_name=${{env.RELEASE_TAG_VERSION}} -f previous_tag_name="0.3.3" -f commitish="main" -f configuration_file_path=".github/release.yml" /repos/cortiqa-playground/Release-notes/releases/generate-notes | jq -r .body );          
          echo "${RESPONSE}" > ${{env.RELEASE_NOTES}} ;
          ls -l ${{env.RELEASE_NOTES}};

      - name: Check release file successfully created
        run: |
          cat release_notes.md;
          
      - name: Pre-process Release Notes
        run: |
          sed -s 's/\([.]*\)by @.*/\1/g' ${{env.RELEASE_NOTES}};
          cat ${{env.RELEASE_NOTES}};

      - name: Create a tag
        run: | 
          gh api --method POST -H "Accept: application/vnd.github+json" -f tag_name=${{env.RELEASE_TAG_VERSION}} -F draft=false -f body=`"cat ${{env.RELEASE_NOTES}}"` -f commitish="main" -F prerelease=true /repos/cortiqa-playground/Release-notes/releases;
          echo "Tag creation successful"

      - name: Check if release notes is attached to the release
        run : |
          cat ${{env.RELEASE_NOTES}};