name: Sample
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
        
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.5'
          channel: 'stable'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      
 #      - name: Install relevant packages
 #       run: |
 #         npm install -g firebase-tools
 #         flutter pub get
